### ISSUE TITLE
Pronouns not showing correctly

### ISSUE THREAD

**Issue by KnightJR8413** [jtint24/Discover-Me#2]
When I tried to put in she/they/their pronouns it showed as she/her/her pronouns afterwards

**Comment by jtint24** [comment]
Thank you for sharing this problem! This issue has been traced to a problem with the autocomplete feature. A patch is on the way!

**Comment by s0menickname** [comment]
I think the best solution would be to make autocompletion feature optional. People are so creative with pronouns it's unpredictable 😅
